pip install black
pip install bokeh
pip install bs4
pip install colorama
pip install dataclasses
pip install datetime
pip install discord
pip install dotenv
pip install flask
pip install isort
pip install json5
pip install keyboard
pip install matplotlib
pip install numpy
pip install pdfplumber
pip install perlin_noise
pip install Pillow
pip install playwright
pip install pyautogui
pip install pygame
pip install pynput
pip install regex
pip install requests
pip install torch
pip install uuid
pip install wcwidth
pip install wcwidth-stubs
